### ISSUE TITLE
Reproducibility definition ?

### ISSUE THREAD

**Issue by zimoun** [tpapp/ReproducibleLiteratePage.jl#1]
Julia is not reproducible; several pre-compilation does not return the same `.ji` files.  See these still open issues:

https://github.com/JuliaLang/julia/issues/25900
https://github.com/JuliaLang/julia/issues/34753

and AFAIK, there is not yet fully fixed.

**Comment by tpapp** [comment]
I think there is a misunderstanding here; "reproducible" in this context means whatever is reproducible with the source code, project, and manifest files. It should be understood that a lot of things aren't, but this package is mainly for posting simple examples.

**Comment by zimoun** [comment]
This is exactly my point.  Today many people are using the term "reproducible" without providing a clear definition about what they speak about.  For instance, in some community, reproducible means bit-to-bit as here https://reproducible-builds.org/.  Other means roughly the same plot.  Other differentiate reproducible vs replication; see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5778115/

Your package is named `ReproducibleLiteratePage` targeting scientific folk.  Then it appears to me useful to explicitly write down what "reproducible" refers to.  As you did in the comment. :-)

**Comment by tpapp** [comment]
Thanks for the clarification, I will address this.
